### ISSUE TITLE
Examples with canvas cannot load canavas themes _themes.json

### ISSUE THREAD

**Issue by QuantumCoderQC** [armory3d/armory_examples_browser#1]
In the examples browser, I get a 404 error in the Chrome developer tools when the browser tries to load the canvas themes file `_themes.json` even if this file is present in the build. Because of this, no example can display the canvas.

**Comment by tong** [comment]
Wondering why?
For example:
https://armory3d.github.io/armory_examples_browser/examples/file_read/_themes.json
→ 404, but exists:
https://github.com/armory3d/armory_examples_browser/blob/gh-pages/examples/file_read/_themes.json

**Comment by QuantumCoderQC** [comment]
Sorry, I forgot to mention. As pointed out by @rpaladin on discord, it's probably due to this: https://github.com/mpetrovich/stylemark/issues/65#issuecomment-492130126

PR #3 should fix this issue.

**Comment by tong** [comment]
Thx, fixed.
