### ISSUE TITLE
missing steps in building the application examples

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory_examples_browser#7]
By the look of it some files needs to be moved and/or renamed before building the Application examples : 

#Build application
haxe app.hxml

returns the following errors : 
src/ArmoryExamplesBrowser.hx:70: characters 49-82 : Warning : Projects directory [web/tutorials] not found
src/ArmoryExamplesBrowser.hx:71: characters 49-82 : Warning : Projects directory [web/templates] not found
src/ArmoryExamplesBrowser.hx:72: characters 47-79 : Warning : Projects directory [web/examples] not found

there is no "web/" folder created when you follow the steps.

**Comment by tong** [comment]
Updated in readme.
